### ISSUE TITLE
Stuck at Downloading Karaoke Mugen

### ISSUE THREAD

**Issue by NiklasHamburgnet** [mjmdurand/mugen-pi#1]
Hi mjmdurand,

At the installation point "Downloading Karaoke Mugen" we are getting a "Username for 'https://gitlab.com':
Sadly the installation is then stuck and we can't input a login. Could you may check, what is causing this error?

Best Regards,
Niklas
 ┌───────────────────────┤ Karaoke Mugen installation ├───────────────────────┐
 │ Downloading Karaoke Mugen                                                                                                                                 │
 │                                                                                                                                                                                       │
 │                                                                                                                                                                                       │
 │                                                                                                                                                                                       │
 │                                                                                               Username for 'https://gitlab.com':                           │
 │                                                                                                                                                                                       │
 └───────────────────────────────────────────────────────────────────┘
 
 
Log.txt is stuck at:

clone to '/root/karaokemugen-app/assets/guestAvatars' ...

**Comment by mjmdurand** [comment]
hello,
Thank you for your feedback ; i'll take a look on this bug asap.

**Comment by mjmdurand** [comment]
Hi @NiklasHamburgnet,
This bug is now fixed.

Many others issues occurred due to the version gap between the old KM version (this script was written for 5.x) and the current KM version (7.x) but they are now all fixed and you should be able to make it properly work.
